version: "3.7"

services:
  service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DBURL=host=db port=5432 user=postgres dbname=gqlpoc sslmode=disable password=password
    depends_on:
      - db
    # command: ["./wait-for", "db:5432", "--", "/main"]
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gqlpoc
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
