version: "3.7"

services:
  worker: &app
    build:
      context: .
      args:
        type: worker
    environment:
      - DATABASE_URL=host=db port=5432 user=postgres dbname=gqlpoc sslmode=disable password=password
      - REDIS_URL=redis://redis/0
    depends_on:
      - db
      - redis
    command: ["./wait-for", "db:5432", "redis:6379", "--", "/main"]
  server:
    <<: *app
    build:
      context: .
      args:
        type: server
    ports:
      - "8080:8080"
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gqlpoc
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
volumes:
  db-data:
