// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/shopspring/decimal"
)

type MutationResponse interface {
	IsMutationResponse()
}

type Address struct {
	Address1 string `json:"address1"`
	Address2 string `json:"address2"`
	City     string `json:"city"`
	State    string `json:"state"`
	Zip      string `json:"zip"`
}

type LoanRequest struct {
	Addresses []*Address      `json:"addresses"`
	Valuation decimal.Decimal `json:"valuation"`
	Principal decimal.Decimal `json:"principal"`
	Interest  decimal.Decimal `json:"interest"`
}

type LoanResponse struct {
	Errors []string `json:"errors"`
	Loan   *Loan    `json:"loan"`
}

func (LoanResponse) IsMutationResponse() {}
